development:
  adapter:  <%= ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_DATABASE'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
